### ISSUE TITLE
Working with Angular?

### ISSUE THREAD

**Issue by jamesplease** [maxogden/requirebin#66]
Require in angular:

``` js
var ng = require('angular');
```

Make a module:

``` js
ng.module('app', []);
```

> Uncaught TypeError: undefined is not a function

Has anyone encountered this? `angularjs` is another npm module that is apparently a browserify shim, but it just causes requirebin to literally explode.

Full error below:
# 

Bundling error: 

---FLAGRANT SYSTEM ERROR---

--- error #0: ---

(logs uuid: 3d1cf350-828b-11e4-af85-ab6c8613f7fd )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'angular' from '/tmp/angularjs1141113-620-1i03dpo/node_modules/angularjs'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:50:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:119:43)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:128:21
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)

dirPath: /tmp/angularjs1141113-620-1i03dpo

---

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

```
https://github.com/jesusabdullah/browserify-cdn/issues
```

Include the ENTIRETY of the contents of this message, and he can
try to help you out.

Have a nice day!

**Comment by LegitTalon** [comment]
I'm not getting that error with this: http://requirebin.com/?gist=782aab770613afc92cf4

**Comment by Alain1405** [comment]
@talon your solution is not available anymore. How did you work around it?

**Comment by talon** [comment]
@Alain1405 I stopped writing Angular :speak_no_evil: so I'm not sure how to fix this, sorry!
