### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by kumavis** [maxogden/requirebin#94]
Getting a build error. This is not requirebins fault, but the module author wanted to know more about the wzrd.in environment.

@wanderer explains that `gmp` is checked for and then falls back to `open ssl`. However it seems that `gmp` appears to be present but is not actually.

```js
Bundling error: 

---FLAGRANT SYSTEM ERROR---

--- error #0: ---


(logs uuid: e01e54c0-da3a-11e4-b2d2-5176a443e15b )

Error: "npm exited with code 1"

code: 1
stdout: 
> bignum@0.9.2 install /tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/node_modules/ethereumjs-p2p/node_modules/ethereumjs-dht/node_modules/ethereumjs-util/node_modules/bignum
> node-gyp configure build

make: Entering directory `/tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/node_modules/ethereumjs-p2p/node_modules/ethereumjs-dht/node_modules/ethereumjs-util/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  SOLINK_MODULE(target) Release/obj.target/bignum.node: Finished
  COPY Release/bignum.node
make: Leaving directory `/tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/node_modules/ethereumjs-p2p/node_modules/ethereumjs-dht/node_modules/ethereumjs-util/node_modules/bignum/build'

> secp256k1@0.0.15 install /tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory `/tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/secp256k1.o
  CC(target) Release/obj.target/secp256k1/secp256k1-src/src/secp256k1.o
make: Leaving directory `/tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/node_modules/secp256k1/build'

> sha3@1.1.0 install /tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/node_modules/sha3
> node-gyp rebuild

make: Entering directory `/tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
  CXX(target) Release/obj.target/sha3/src/displayIntermediateValues.o
  CXX(target) Release/obj.target/sha3/src/KeccakF-1600-reference.o
  CXX(target) Release/obj.target/sha3/src/KeccakNISTInterface.o
  CXX(target) Release/obj.target/sha3/src/KeccakSponge.o
  SOLINK_MODULE(target) Release/obj.target/sha3.node
  SOLINK_MODULE(target) Release/obj.target/sha3.node: Finished
  COPY Release/sha3.node
make: Leaving directory `/tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/node_modules/sha3/build'

stderr: npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/bigi
npm http GET https://registry.npmjs.org/crypto-js
npm http GET https://registry.npmjs.org/ethereumjs-util/0.0.8
npm http GET https://registry.npmjs.org/ecdsa
npm http GET https://registry.npmjs.org/merkle-patricia-tree
npm http GET https://registry.npmjs.org/ecurve
npm http GET https://registry.npmjs.org/secp256k1/0.0.15
npm http GET https://registry.npmjs.org/rlp/0.0.12
npm http GET https://registry.npmjs.org/sha3
npm http GET https://registry.npmjs.org/ethereumjs-p2p/0.0.2
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/bn.js
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/bigi
npm http 304 https://registry.npmjs.org/crypto-js
npm http 304 https://registry.npmjs.org/merkle-patricia-tree
npm http 304 https://registry.npmjs.org/ethereumjs-util/0.0.8
npm http 304 https://registry.npmjs.org/rlp/0.0.12
npm http 304 https://registry.npmjs.org/ecdsa
npm http 304 https://registry.npmjs.org/secp256k1/0.0.15
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/bn.js
npm http 304 https://registry.npmjs.org/sha3
npm http 304 https://registry.npmjs.org/ethereumjs-p2p/0.0.2
npm http 304 https://registry.npmjs.org/ecurve
npm http GET https://registry.npmjs.org/ethereumjs-dht/0.0.1
npm http GET https://registry.npmjs.org/server-destroy
npm http 304 https://registry.npmjs.org/server-destroy
npm http 304 https://registry.npmjs.org/ethereumjs-dht/0.0.1
npm http GET https://registry.npmjs.org/memdown
npm http GET https://registry.npmjs.org/levelup
npm http GET https://registry.npmjs.org/semaphore
npm http 304 https://registry.npmjs.org/semaphore
npm http 304 https://registry.npmjs.org/memdown
npm http 304 https://registry.npmjs.org/levelup
npm http GET https://registry.npmjs.org/ethereumjs-util/0.0.7
npm http GET https://registry.npmjs.org/k-bucket
npm http 304 https://registry.npmjs.org/k-bucket
npm http 304 https://registry.npmjs.org/ethereumjs-util/0.0.7
npm http GET https://registry.npmjs.org/bignum-browserify/0.0.1
npm http GET https://registry.npmjs.org/bignum
npm http 304 https://registry.npmjs.org/bignum
npm http 304 https://registry.npmjs.org/bignum-browserify/0.0.1
npm http GET https://registry.npmjs.org/abstract-leveldown
npm http GET https://registry.npmjs.org/functional-red-black-tree
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/ltgt
npm http 304 https://registry.npmjs.org/abstract-leveldown
npm http 304 https://registry.npmjs.org/functional-red-black-tree
npm http 304 https://registry.npmjs.org/ltgt
npm http GET https://registry.npmjs.org/buffer-equal/0.0.1
npm http GET https://registry.npmjs.org/jsbn/0.0.0
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/buffer-equal/0.0.1
npm http 304 https://registry.npmjs.org/jsbn/0.0.0
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/errno
npm http GET https://registry.npmjs.org/prr
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/deferred-leveldown
npm http 304 https://registry.npmjs.org/errno
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/prr
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/deferred-leveldown
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings
cc1plus: warning: command line option ‘-std=c11’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from ../secp256k1-src/src/num.h:17:0,
                 from ../secp256k1-src/src/num_impl.h:14,
                 from ../secp256k1-src/src/secp256k1.c:12:
../secp256k1-src/src/num_gmp.h:10:17: fatal error: gmp.h: No such file or directory
 #include 
                 ^
compilation terminated.
make: *** [Release/obj.target/secp256k1/secp256k1-src/src/secp256k1.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/admin/browserify-cdn/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.8.0-19-generic
gyp ERR! command "node" "/home/admin/browserify-cdn/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/node_modules/secp256k1
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 

npm ERR! secp256k1@0.0.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@0.0.15 install script.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.8.0-19-generic
npm ERR! command "node" "/home/admin/browserify-cdn/node_modules/.bin/npm" "install" "--production"
npm ERR! cwd /tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.3.26
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/ethereumjs-lib11533-32164-q9f74b/node_modules/ethereumjs-lib/npm-debug.log
npm ERR! not ok code 0

dirPath: /tmp/ethereumjs-lib11533-32164-q9f74b


------

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jfhbrook/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and the maintainer(s)
can try to help you out.

Have a nice day!
```

**Comment by wanderer** [comment]
yes it would be very helpful it i know OS your are running.

**Comment by maxogden** [comment]
Linux wzrd 3.8.0-19-generic #30-Ubuntu SMP Wed May 1 16:35:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
